import { useState } from "react";
import { View, StyleSheet, TouchableOpacity, ActivityIndicator } from "react-native";
import { Text } from "../../src/components/AppText";
import { CameraView, useCameraPermissions } from "expo-camera";
import * as Location from "expo-location";
import { apiClient, apiErrorMessage } from "../../src/api/client";
import { useAuth } from "../../src/auth/AuthContext";
import { colors, radius } from "../../src/theme";

const MOCK_SCAN_OUTCOMES = [
  { type: "success" as const, text: "Stamp added! 4 / 5" },
  { type: "success" as const, text: "Reward unlocked!\nShow code 482913 to staff." },
];

export default function ScanScreen() {
  const { isPreview } = useAuth(); const [permission, requestPermission] = useCameraPermissions(); const [scanned, setScanned] = useState(false); const [loading, setLoading] = useState(false); const [resultMessage, setResultMessage] = useState<{ type: "success" | "error"; text: string } | null>(null); const [previewOutcomeIndex, setPreviewOutcomeIndex] = useState(0);
  function handleSimulateScan() { setResultMessage(MOCK_SCAN_OUTCOMES[previewOutcomeIndex]); setPreviewOutcomeIndex((i) => (i + 1) % MOCK_SCAN_OUTCOMES.length); }
  function parseScannedValue(raw: string): { qrToken?: string; branchId?: string } { if (raw.startsWith("http://") || raw.startsWith("https://") || raw.startsWith("thappa://")) { try { const url = new URL(raw.replace("thappa://", "https://placeholder/")); return { branchId: url.searchParams.get("b") || undefined }; } catch { return {}; } } return { qrToken: raw }; }
  async function handleBarcodeScanned({ data }: { data: string }) { if (scanned || loading) return; setScanned(true); if (isPreview) return handleSimulateScan(); setLoading(true); setResultMessage(null); try { const { qrToken, branchId } = parseScannedValue(data); let body: Record<string, unknown>; if (qrToken) body = { qrToken }; else if (branchId) { const { status } = await Location.requestForegroundPermissionsAsync(); if (status !== "granted") { setResultMessage({ type: "error", text: "Location permission is required to collect a stamp here." }); setLoading(false); return; } const position = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); body = { branchId, lat: position.coords.latitude, lng: position.coords.longitude }; } else throw new Error("Unrecognized QR code"); const { data: response } = await apiClient.post("/customer/stamps/redeem-qr", body); setResultMessage(response.rewardUnlocked ? { type: "success", text: `Reward unlocked!\n${response.redemption.rewardDescription}\nShow code ${response.redemption.redemptionCode} to staff.` } : { type: "success", text: `Stamp added! ${response.stampCard.currentStamps} / ${response.stampCard.stampsRequired}` }); } catch (err) { setResultMessage({ type: "error", text: apiErrorMessage(err) }); } finally { setLoading(false); } }
  function scanAgain() { setScanned(false); setResultMessage(null); }
  if (!permission) return <View style={styles.center}><ActivityIndicator color={colors.forest} /></View>;
  if (!permission.granted && !resultMessage) return <View style={styles.center}><View style={styles.permissionIcon}><Text style={styles.permissionIconText}>⌁</Text></View><Text style={styles.permissionTitle}>Ready when you are.</Text><Text style={styles.permissionText}>Allow camera access to scan a Thappa code and collect your next stamp.</Text><TouchableOpacity style={styles.button} onPress={requestPermission}><Text style={styles.buttonText}>Allow camera access</Text></TouchableOpacity>{isPreview && <TouchableOpacity style={styles.previewButton} onPress={handleSimulateScan}><Text style={styles.previewText}>Preview a scan</Text></TouchableOpacity>}</View>;
  return <View style={styles.container}>{!resultMessage ? <><CameraView style={StyleSheet.absoluteFillObject} barcodeScannerSettings={{ barcodeTypes: ["qr"] }} onBarcodeScanned={scanned ? undefined : handleBarcodeScanned} /><View style={styles.shade}><View style={styles.scanTop}><Text style={styles.scanEyebrow}>THAPPA SCANNER</Text><Text style={styles.scanTitle}>Find the QR code.</Text></View><View style={styles.frame}><View style={[styles.corner, styles.topLeft]} /><View style={[styles.corner, styles.topRight]} /><View style={[styles.corner, styles.bottomLeft]} /><View style={[styles.corner, styles.bottomRight]} /></View><View style={styles.scanBottom}><Text style={styles.hint}>{loading ? "Checking your stamp..." : "Hold steady — we’ll do the rest."}</Text>{isPreview && <TouchableOpacity style={styles.previewButton} onPress={handleSimulateScan}><Text style={styles.previewText}>Preview a scan</Text></TouchableOpacity>}</View></View></> : <View style={styles.resultContainer}><View style={[styles.resultIcon, resultMessage.type === "error" && styles.errorIcon]}><Text style={styles.resultIconText}>{resultMessage.type === "success" ? "✦" : "!"}</Text></View><Text style={resultMessage.type === "success" ? styles.resultSuccess : styles.resultError}>{resultMessage.text}</Text><Text style={styles.resultSub}>{resultMessage.type === "success" ? "That’s one step closer to something good." : "Give it another go, or ask the team at the counter."}</Text><TouchableOpacity style={styles.button} onPress={scanAgain}><Text style={styles.buttonText}>Scan another code  →</Text></TouchableOpacity></View>}</View>;
}

const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.ink }, center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 28, backgroundColor: colors.cream }, permissionIcon: { backgroundColor: colors.yellow, width: 58, height: 58, borderRadius: 20, alignItems: "center", justifyContent: "center", marginBottom: 18 }, permissionIconText: { color: colors.ink, fontSize: 27, fontWeight: "900" }, permissionTitle: { color: colors.ink, fontSize: 23, fontWeight: "900" }, permissionText: { color: colors.muted, fontSize: 14, lineHeight: 20, textAlign: "center", marginTop: 8, marginBottom: 22 }, button: { backgroundColor: colors.forest, borderRadius: radius.pill, paddingVertical: 15, paddingHorizontal: 22, alignItems: "center" }, buttonText: { color: colors.white, fontSize: 14, fontWeight: "900" }, shade: { flex: 1, justifyContent: "space-between", padding: 23, backgroundColor: "rgba(26, 43, 32, 0.30)" }, scanTop: { marginTop: 12 }, scanEyebrow: { color: colors.yellow, fontWeight: "900", fontSize: 10, letterSpacing: 1.4 }, scanTitle: { color: colors.white, fontSize: 25, fontWeight: "900", marginTop: 5 }, frame: { width: 244, height: 244, alignSelf: "center", position: "relative" }, corner: { position: "absolute", width: 45, height: 45, borderColor: colors.yellow }, topLeft: { top: 0, left: 0, borderTopWidth: 5, borderLeftWidth: 5, borderTopLeftRadius: 19 }, topRight: { top: 0, right: 0, borderTopWidth: 5, borderRightWidth: 5, borderTopRightRadius: 19 }, bottomLeft: { bottom: 0, left: 0, borderBottomWidth: 5, borderLeftWidth: 5, borderBottomLeftRadius: 19 }, bottomRight: { bottom: 0, right: 0, borderBottomWidth: 5, borderRightWidth: 5, borderBottomRightRadius: 19 }, scanBottom: { alignItems: "center", marginBottom: 13 }, hint: { color: colors.white, fontSize: 14, fontWeight: "700", marginBottom: 15 }, previewButton: { paddingHorizontal: 15, paddingVertical: 10, borderRadius: radius.pill, backgroundColor: colors.yellowSoft }, previewText: { color: colors.ink, fontSize: 12, fontWeight: "900" }, resultContainer: { flex: 1, backgroundColor: colors.cream, alignItems: "center", justifyContent: "center", padding: 30 }, resultIcon: { width: 72, height: 72, borderRadius: 25, backgroundColor: colors.yellow, alignItems: "center", justifyContent: "center" }, errorIcon: { backgroundColor: colors.yellow }, resultIconText: { color: colors.ink, fontSize: 30, fontWeight: "900" }, resultSuccess: { color: colors.ink, fontSize: 23, fontWeight: "900", lineHeight: 30, textAlign: "center", marginTop: 20 }, resultError: { color: colors.danger, fontSize: 20, fontWeight: "900", lineHeight: 27, textAlign: "center", marginTop: 20 }, resultSub: { color: colors.muted, fontSize: 13, lineHeight: 19, textAlign: "center", marginTop: 8, marginBottom: 24 }, });
