import { useEffect, useRef, useState } from "react";
import { View, TextInput, TouchableOpacity, StyleSheet, KeyboardAvoidingView, Platform, Alert, Image } from "react-native";
import { Text } from "../../src/components/AppText";
import Constants from "expo-constants";
import { useRouter } from "expo-router";
import { FirebaseRecaptchaVerifierModal } from "expo-firebase-recaptcha";
import { PhoneAuthProvider } from "firebase/auth";
import { apiClient, apiErrorMessage } from "../../src/api/client";
import { useAuth } from "../../src/auth/AuthContext";
import { firebaseAuth, firebaseEnabled } from "../../src/auth/firebase";
import { useGoogleIdToken } from "../../src/auth/useGoogleIdToken";
import { colors, fonts, radius } from "../../src/theme";

const GOOGLE_CLIENT_ID = (Constants.expoConfig?.extra?.googleClientId as string) || "";
const firebaseExtra = (Constants.expoConfig?.extra?.firebase || {}) as Record<string, string>;

export default function LoginScreen() {
  const [phone, setPhone] = useState(""); const [name, setName] = useState(""); const [loading, setLoading] = useState(false);
  const router = useRouter(); const { login, previewLogin } = useAuth(); const recaptchaVerifier = useRef<FirebaseRecaptchaVerifierModal>(null);
  const { request: googleRequest, idToken: googleIdToken, promptAsync: promptGoogle } = useGoogleIdToken(GOOGLE_CLIENT_ID);
  useEffect(() => { if (googleIdToken) handleGoogleIdToken(googleIdToken); }, [googleIdToken]);
  async function handleGoogleIdToken(idToken: string) { setLoading(true); try { const { data } = await apiClient.post("/auth/google", { idToken }); await login(data.user, data.accessToken, data.refreshToken); } catch (err) { Alert.alert("Google sign-in failed", apiErrorMessage(err)); } finally { setLoading(false); } }
  function handleGooglePress() { if (!GOOGLE_CLIENT_ID) return Alert.alert("Google Sign-In not configured", "Set EXPO_PUBLIC_GOOGLE_CLIENT_ID (mobile) and GOOGLE_CLIENT_ID (backend) to a Google OAuth Web Client ID to enable this."); promptGoogle(); }
  async function handleSendOtp() { if (!phone) return Alert.alert("Enter your phone number"); setLoading(true); try { if (firebaseEnabled && firebaseAuth) { const verificationId = await new PhoneAuthProvider(firebaseAuth).verifyPhoneNumber(phone, recaptchaVerifier.current!); router.push({ pathname: "/(auth)/verify-otp", params: { phone, name, verificationId } }); } else { await apiClient.post("/auth/otp/send", { phone }); router.push({ pathname: "/(auth)/verify-otp", params: { phone, name } }); } } catch (err) { Alert.alert("Couldn't send OTP", apiErrorMessage(err)); } finally { setLoading(false); } }
  return <KeyboardAvoidingView style={styles.container} behavior={Platform.OS === "ios" ? "padding" : undefined}>{firebaseEnabled && <FirebaseRecaptchaVerifierModal ref={recaptchaVerifier} firebaseConfig={firebaseExtra} attemptInvisibleVerification />}<View style={styles.top}><Image source={require("../../assets/thappa logo.jpeg")} style={styles.logo} resizeMode="contain" /><Text style={styles.tagline}>Little stamps. Big mood.</Text><Text style={styles.spark}>✦</Text></View><View style={styles.form}><Text style={styles.formTitle}>Let’s get you in.</Text><Text style={styles.formSub}>Your favourites and rewards are waiting.</Text><Text style={styles.label}>YOUR NAME</Text><TextInput style={styles.input} placeholder="Sana Khan" placeholderTextColor={colors.ink} value={name} onChangeText={setName} /><Text style={styles.label}>PHONE NUMBER</Text><TextInput style={styles.input} placeholder="+92 300 1234567" placeholderTextColor={colors.ink} keyboardType="phone-pad" value={phone} onChangeText={setPhone} /><TouchableOpacity style={styles.primaryButton} onPress={handleSendOtp} disabled={loading}><Text style={styles.primaryButtonText}>{loading ? "Sending..." : "Send me a code  →"}</Text></TouchableOpacity><View style={styles.orLine}><View style={styles.rule} /><Text style={styles.orText}>OR</Text><View style={styles.rule} /></View><TouchableOpacity style={styles.googleButton} onPress={handleGooglePress} disabled={loading || (!!GOOGLE_CLIENT_ID && !googleRequest)}><Text style={styles.googleButtonText}>Continue with Google</Text></TouchableOpacity>{__DEV__ && <TouchableOpacity style={styles.guestButton} onPress={previewLogin} disabled={loading}><Text style={styles.guestButtonText}>Preview the app</Text></TouchableOpacity>}</View></KeyboardAvoidingView>;
}

const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.forest, justifyContent: "flex-end" }, top: { flex: 1, alignItems: "center", justifyContent: "center", paddingTop: 35 }, logo: { height: 128, width: 190, borderRadius: 22 }, tagline: { color: colors.yellow, fontSize: 16, fontWeight: "900", marginTop: 12 }, spark: { color: colors.coral, fontSize: 27, position: "absolute", top: "31%", right: "24%" }, form: { backgroundColor: colors.cream, borderTopLeftRadius: 32, borderTopRightRadius: 32, padding: 23, paddingBottom: 34 }, formTitle: { color: colors.ink, fontSize: 24, fontWeight: "900", letterSpacing: -0.5 }, formSub: { color: colors.muted, fontSize: 13, marginTop: 4 }, label: { color: colors.ink, fontSize: 10, fontWeight: "900", letterSpacing: 1, marginTop: 17, marginBottom: 6 }, input: { backgroundColor: colors.paper, borderRadius: radius.small, paddingHorizontal: 14, paddingVertical: 12, color: colors.ink, fontFamily: fonts.semibold, fontSize: 15 }, primaryButton: { backgroundColor: colors.forest, borderRadius: radius.pill, paddingVertical: 15, alignItems: "center", marginTop: 20 }, primaryButtonText: { color: colors.white, fontWeight: "900", fontSize: 14 }, orLine: { flexDirection: "row", alignItems: "center", gap: 10, marginVertical: 15 }, rule: { height: 1, flex: 1, backgroundColor: colors.line }, orText: { color: colors.muted, fontSize: 10, fontWeight: "900" }, googleButton: { backgroundColor: colors.paper, borderRadius: radius.pill, paddingVertical: 14, alignItems: "center" }, googleButtonText: { color: colors.ink, fontWeight: "800", fontSize: 14 }, guestButton: { alignItems: "center", marginTop: 13 }, guestButtonText: { color: colors.forest, fontSize: 12, fontWeight: "800", textDecorationLine: "underline" }, });
